bid_type_Standard = {'Pre-Qualification': "Request for Pre-Qualification(RFPQ)",
                     'Tender': "Request for Tender(RFT)",
                     'RFP': "Request for Proposal(RFP)",
                     'Notice of Contract Award': "Request for Proposal(RFP)",
                     'RFI': 'Request for Information (RFI)',
                     'EOI': 'Others',
                     'RFQ': "Request for Quotation(RFQ)",
                     'Request for Tender': "Request for Tender(RFT)",
                     'Request for Proposal': "Request for Proposal(RFP)",
                     'Consultant Selection': "Request for Pre-Qualification(RFPQ)",
                     'Consultant Selection Stage 1': "Request for Pre-Qualification(RFPQ)",
                     'Expression of Interest': 'Others',
                     'Request for Quote': "Request for Quotation(RFQ)",
                     'Consultant Selection Stage 2': "Request for Pre-Qualification(RFPQ)",
                     'Cooperative Tender': "Request for Tender(RFT)",
                     'Request for Tender (Carpentry)': "Request for Tender(RFT)",
                     'Request For Proposal': "Request for Proposal(RFP)",
                     'Request For PreQualification': "Request for Pre-Qualification(RFPQ)",
                     'Request for Quotation': "Request for Quotation(RFQ)",
                     'RFT': "Request for Tender(RFT)",
                     'Request for Offer': 'Others',
                     'Request For Tender': "Request for Tender(RFT)",
                     'Request For Quotation': "Request for Quotation(RFQ)",
                     'Request for Proposal(N)': "Request for Proposal(RFP)",
                     'RFPQ': "Request for Pre-Qualification(RFPQ)",
                     'N': 'Others',
                     'NRFP': 'Others',
                     'Request For Quotations': "Request for Quotation(RFQ)",
                     'Request for Supplier Pre-qualification': "Request for Pre-Qualification(RFPQ)",
                     'ITT': "Request for Tender(RFT)",
                     'RFSQ': "Request for Pre-Qualification(RFPQ)",
                     'RFEOI': 'Others',
                     'Request for Qualifications': "Request for Pre-Qualification(RFPQ)",
                     'Request for Quotation (Formal)': "Request for Quotation(RFQ)",
                     'Informal Request for Quotation': "Request for Quotation(RFQ)",
                     'Request for Information': 'Request for Information (RFI)',
                     'Request For Supplier Qualification': "Request for Pre-Qualification(RFPQ)",
                     'RFT - Public Works': "Request for Tender(RFT)",
                     'RFT - Construction - Stipulated Price - CCDC': "Request for Tender(RFT)",
                     'RFT - Construction - Unit Price': "Request for Tender(RFT)",
                     'RFT - Goods and Services': "Request for Tender(RFT)",
                     'RFP - Goods and Services': "Request for Tender(RFT)",
                     'RFT - Vehicle': "Request for Tender(RFT)",
                     'RFRC': "Request for Proposal(RFP)",
                     'RFT - Revenue Generating': "Request for Tender(RFT)",
                     'RFP - Prime Consultant': "Request for Proposal(RFP)",
                     'RFP - Revenue Generating': "Request for Proposal(RFP)",
                     'RFQ (<)': "Request for Quotation(RFQ)",
                     'RFD (Disposal)': 'Others',
                     'Notice': 'Others',
                     'Non-Standard Procurement': 'Others',
                     'RFQ – Low Bid': "Request for Quotation(RFQ)",
                     'RFQ – High Score': "Request for Quotation(RFQ)",
                     'RFP – Consecutive Negotiation': "Request for Proposal(RFP)",
                     'RFSQ – Prequalification': "Request for Pre-Qualification(RFPQ)",
                     'DN': "Request for Quotation(RFQ)",
                     'VOR': "Request for Proposal(RFP)",
                     'RFO': 'Others'}